image: beevelop/ionic:latest

stages:
  - prepare
  - build

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./android/gradlew

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

prepare_node:
  stage: prepare
  script:
    - ls
    - npm install
    - rm -rf "www"
    - npx cap copy
    - npx cap sync

build_android:
  stage: build
  script:
    - npx cap copy android
    - cd ./android
    - ./gradlew assembleRelease
    - ls ./android/app/build/outputs/apk/release/*.apk
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      -Pandroid.injected.signing.key.password=$KEY_PASSWORD
  artifacts:
    paths:
      - android/app/build/outputs/apk/release
